/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'blogCategory';
  };
  minRead?: number;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  publishedAt?: string;
  mainImage?: BlockImage;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type BlockImage = {
  _type: 'blockImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Career = {
  _id: string;
  _type: 'career';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  department?:
    | 'engineer'
    | 'operations'
    | 'growth-&-marketing'
    | 'design'
    | 'marchandising'
    | 'support'
    | 'marketing'
    | 'people'
    | 'sales';
  body?: BlockContent;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type Store = {
  _id: string;
  _type: 'store';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  mainImage?: BlockImage;
  lat?: number;
  long?: number;
  continent?: 'north-america' | 'south-america' | 'europe' | 'asia';
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: BlockImage;
  body?: string;
  socialLink?: string;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  position?: string;
  mainImage?: BlockImage;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  sku?: string;
  slug?: Slug;
  basePrice?: number;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'productCategory';
  };
  brand?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'productBrand';
  };
  variants?: Array<{
    sku?: string;
    color?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'productColor';
    };
    size?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'productSize';
    };
    stock?: number;
    priceOverride?: number;
    fit?: 'slim-fit' | 'oversized' | 'petite' | 'tall';
    mainImages?: Array<
      {
        _key: string;
      } & BlockImage
    >;
    _type: 'variant';
    _key: string;
  }>;
  tag?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'productTag';
  }>;
  body?: BlockContent;
  status?: 'draft' | 'published';
};

export type ProductTag = {
  _id: string;
  _type: 'productTag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type ProductBrand = {
  _id: string;
  _type: 'productBrand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: BlockImage;
};

export type ProductSize = {
  _id: string;
  _type: 'productSize';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type ProductColor = {
  _id: string;
  _type: 'productColor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type ProductCategory = {
  _id: string;
  _type: 'productCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Blog
  | BlockContent
  | BlockImage
  | Slug
  | Career
  | Faq
  | UtilityPage
  | Store
  | Author
  | BlogCategory
  | TeamMember
  | Product
  | ProductTag
  | ProductBrand
  | ProductSize
  | ProductColor
  | ProductCategory
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: {  "products": *[_type == 'product'               && defined(slug.current)]               [$startIndex...$endIndex]               |order(_createdAt){                  name,                  "slug": slug.current,                  "category": category->.name,                  basePrice,                  "imageUrl": variants[0].mainImages[0].asset->.url,                  "imageAlt": variants[0].mainImages[0].alt               },  "total": count(*[_type == 'product'               && defined(slug.current)])}
export type ALL_PRODUCTS_QUERYResult = {
  products: Array<{
    name: string | null;
    slug: string | null;
    category: string | null;
    basePrice: number | null;
    imageUrl: string | null;
    imageAlt: string | null;
  }>;
  total: number;
};
// Variable: PRODUCT_QUERY
// Query: *[_type == 'product' && slug.current == $slug][0]{  name,  sku,  "slug": slug.current,  basePrice,  "category": category->name,  "brand": brand->name,  "variants": variants[]{    sku,    "color": color->name,    "size": size->size,    stock,    priceOverride,    fit,    "images": mainImages[]{      "imageUrl": asset->url,      "imageAlt": alt    }  },  "tag": tag[0]->name,  status,  body }
export type PRODUCT_QUERYResult = {
  name: string | null;
  sku: string | null;
  slug: string | null;
  basePrice: number | null;
  category: string | null;
  brand: string | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: null;
    stock: number | null;
    priceOverride: number | null;
    fit: 'oversized' | 'petite' | 'slim-fit' | 'tall' | null;
    images: Array<{
      imageUrl: string | null;
      imageAlt: string | null;
    }> | null;
  }> | null;
  tag: string | null;
  status: 'draft' | 'published' | null;
  body: BlockContent | null;
} | null;
// Variable: ALL_BLOGS_QUERY
// Query: {  "blogs": *[_type == 'blog'            && defined(slug.current)            && (              (!defined($category)) || count($category) == 0 || category->slug.current in $category            )]            [$startIndex...$endIndex]            | order(publishedAt){              name,              "slug": slug.current,              publishedAt,              "imageUrl": mainImage.asset->.url,              "imageAlt": mainImage.alt,              "category": category->.name,              "author": author->.name,            },  "total": count(*[_type == 'blog'            && defined(slug.current)            && (              (!defined($category)) || count($category) == 0 || category->slug.current in $category            )])}
export type ALL_BLOGS_QUERYResult = {
  blogs: Array<{
    name: string | null;
    slug: string | null;
    publishedAt: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    category: string | null;
    author: string | null;
  }>;
  total: number;
};
// Variable: ALL_BLOG_CATEGORIES_QUERY
// Query: *[_type == 'blogCategory' && defined(slug.current)]{  name,  "slug": slug.current }
export type ALL_BLOG_CATEGORIES_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
}>;
// Variable: BLOG_QUERY
// Query: *[_type == 'blog' && slug.current == $slug][0]{  name,  "slug": slug.current,  publishedAt,  minRead,  "category": category->name,  author->{    name,    "slug": slug.current  },  body,  "imageUrl": mainImage.asset->.url,  "imageAlt": mainImage.alt }
export type BLOG_QUERYResult = {
  name: string | null;
  slug: string | null;
  publishedAt: string | null;
  minRead: number | null;
  category: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  body: BlockContent | null;
  imageUrl: string | null;
  imageAlt: string | null;
} | null;
// Variable: ALL_FAQS_QUERY
// Query: *[_type == 'faq' && defined(slug.current)]{  name,  "slug": slug.current,  faqs[]{    question,    answer,    _key  } }
export type ALL_FAQS_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
  faqs: Array<{
    question: string | null;
    answer: string | null;
    _key: string;
  }> | null;
}>;
// Variable: ALL_MEMBERS_QUERY
// Query: {  "members": *[_type == 'teamMember'              && defined(slug.current)]{                name,                "slug": slug.current,                position,                "imageUrl": mainImage.asset->.url,                "imageAlt": mainImage.alt                 },  "total": count(*[_type == 'teamMember'              && defined(slug.current)])}
export type ALL_MEMBERS_QUERYResult = {
  members: Array<{
    name: string | null;
    slug: string | null;
    position: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
  }>;
  total: number;
};
// Variable: UTILITY_PAGE_QUERY
// Query: *[_type == 'utilityPage' && slug.current == $slug][0]{  name,  "slug": slug.current,  body,  "title": seo.title,  "description": seo.description }
export type UTILITY_PAGE_QUERYResult = {
  name: string | null;
  slug: string | null;
  body: BlockContent | null;
  title: string | null;
  description: string | null;
} | null;
// Variable: ALL_STORES_QUERY
// Query: {  "stores": *[_type == 'store'             && defined(slug.current)             && (              (!defined($country)) || count($country) == 0 || country in $country             )             &&(              (!defined($continent)) || count($continent) == 0 || continent in $continent             )             ]             [$startIndex...$endIndex]             |order(name){              name,              "slug": slug.current,              city,              country,              continent,              "imageUrl": mainImage.asset->.url,              "imageAlt": mainImage.alt              },  "total": count(*[_type == 'store'             && defined(slug.current)             && (              (!defined($country)) || count($country) == 0 || country in $country             )             &&(              (!defined($continent)) || count($continent) == 0 || continent in $continent             )             ])}
export type ALL_STORES_QUERYResult = {
  stores: Array<{
    name: string | null;
    slug: string | null;
    city: string | null;
    country: string | null;
    continent: 'asia' | 'europe' | 'north-america' | 'south-america' | null;
    imageUrl: string | null;
    imageAlt: string | null;
  }>;
  total: number;
};
// Variable: STORE_QUERY
// Query: *[_type == 'store'&& slug.current == $slug][0]{              name,              "slug": slug.current,              address1,              address2,              city,              zip,              state,              country,              lat,              long,              "imageUrl": mainImage.asset->.url,              "imageAlt": mainImage.alt}
export type STORE_QUERYResult = {
  name: string | null;
  slug: string | null;
  address1: string | null;
  address2: string | null;
  city: string | null;
  zip: string | null;
  state: string | null;
  country: string | null;
  lat: number | null;
  long: number | null;
  imageUrl: string | null;
  imageAlt: string | null;
} | null;
// Variable: ALL_AUTHORS_QUERY
// Query: *[_type == 'author' && defined(slug.current)]{  name,  "slug": slug.current,  "imageUrl": mainImage.asset->.url,  "imageAlt": mainImage.alt }
export type ALL_AUTHORS_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
}>;
// Variable: AUTHOR_QUERY
// Query: {  "author": *[_type == 'author'              && slug.current == $slug][0]{              name,              "slug": slug.current,              body,              socialLink,              "imageUrl": mainImage.asset->.url,              "imageAlt": mainImage.alt             },  "blogs": *[_type == 'blog'            && author->slug.current == $slug]{              name,              "slug": slug.current,              publishedAt,              "imageUrl": mainImage.asset->.url,              "imageAlt": mainImage.alt,              "category": category->.name,              "author": author->.name,            }}
export type AUTHOR_QUERYResult = {
  author: {
    name: string | null;
    slug: string | null;
    body: string | null;
    socialLink: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
  } | null;
  blogs: Array<{
    name: string | null;
    slug: string | null;
    publishedAt: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    category: string | null;
    author: string | null;
  }>;
};
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == 'product'  && defined(slug.current)  && (    (!defined($search))    || name match ($search + "*")    || variants[].color->name match ($search + "*")    || variants[].size->name match ($search + "*")  )]{  name,  "slug": slug.current,  "category": category->name,  basePrice,  "imageUrl": mainImages[0].asset->url,  "imageAlt": mainImages[0].alt}
export type SEARCH_PRODUCTS_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
  category: string | null;
  basePrice: number | null;
  imageUrl: null;
  imageAlt: null;
}>;
// Variable: SEARCH_BLOGS_QUERY
// Query: *[  _type == 'blog'  && defined(slug.current)  && (    (!defined($search))    || name match ($search + "*")    || category->name match ($search + "*")    || author->name match ($search + "*")  )]{  name,  "slug": slug.current,  publishedAt,  "imageUrl": mainImage.asset->.url,  "imageAlt": mainImage.alt,  "category": category->.name,  "author": author->.name,}
export type SEARCH_BLOGS_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
  publishedAt: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  category: string | null;
  author: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '{\n  "products": *[_type == \'product\'\n               && defined(slug.current)]\n               [$startIndex...$endIndex]\n               |order(_createdAt){\n                  name,\n                  "slug": slug.current,\n                  "category": category->.name,\n                  basePrice,\n                  "imageUrl": variants[0].mainImages[0].asset->.url,\n                  "imageAlt": variants[0].mainImages[0].alt\n               },\n  "total": count(*[_type == \'product\'\n               && defined(slug.current)])\n}': ALL_PRODUCTS_QUERYResult;
    '*[_type == \'product\'\n && slug.current == $slug][0]{\n  name,\n  sku,\n  "slug": slug.current,\n  basePrice,\n  "category": category->name,\n  "brand": brand->name,\n  "variants": variants[]{\n    sku,\n    "color": color->name,\n    "size": size->size,\n    stock,\n    priceOverride,\n    fit,\n    "images": mainImages[]{\n      "imageUrl": asset->url,\n      "imageAlt": alt\n    }\n  },\n  "tag": tag[0]->name,\n  status,\n  body\n }': PRODUCT_QUERYResult;
    '{\n  "blogs": *[_type == \'blog\'\n            && defined(slug.current)\n            && (\n              (!defined($category)) || count($category) == 0 || category->slug.current in $category\n            )]\n            [$startIndex...$endIndex]\n            | order(publishedAt){\n              name,\n              "slug": slug.current,\n              publishedAt,\n              "imageUrl": mainImage.asset->.url,\n              "imageAlt": mainImage.alt,\n              "category": category->.name,\n              "author": author->.name,\n            },\n  "total": count(*[_type == \'blog\'\n            && defined(slug.current)\n            && (\n              (!defined($category)) || count($category) == 0 || category->slug.current in $category\n            )])\n}': ALL_BLOGS_QUERYResult;
    '*[_type == \'blogCategory\'\n && defined(slug.current)]{\n  name,\n  "slug": slug.current\n }': ALL_BLOG_CATEGORIES_QUERYResult;
    '*[_type == \'blog\'\n && slug.current == $slug][0]{\n  name,\n  "slug": slug.current,\n  publishedAt,\n  minRead,\n  "category": category->name,\n  author->{\n    name,\n    "slug": slug.current\n  },\n  body,\n  "imageUrl": mainImage.asset->.url,\n  "imageAlt": mainImage.alt\n }': BLOG_QUERYResult;
    '*[_type == \'faq\'\n && defined(slug.current)]{\n  name,\n  "slug": slug.current,\n  faqs[]{\n    question,\n    answer,\n    _key\n  }\n }': ALL_FAQS_QUERYResult;
    '{\n  "members": *[_type == \'teamMember\'\n              && defined(slug.current)]{\n                name,\n                "slug": slug.current,\n                position,\n                "imageUrl": mainImage.asset->.url,\n                "imageAlt": mainImage.alt   \n              },\n  "total": count(*[_type == \'teamMember\'\n              && defined(slug.current)])\n}': ALL_MEMBERS_QUERYResult;
    '*[_type == \'utilityPage\'\n && slug.current == $slug][0]{\n  name,\n  "slug": slug.current,\n  body,\n  "title": seo.title,\n  "description": seo.description\n }': UTILITY_PAGE_QUERYResult;
    '{\n  "stores": *[_type == \'store\'\n             && defined(slug.current)\n             && (\n              (!defined($country)) || count($country) == 0 || country in $country\n             )\n             &&(\n              (!defined($continent)) || count($continent) == 0 || continent in $continent\n             )\n             ]\n             [$startIndex...$endIndex]\n             |order(name){\n              name,\n              "slug": slug.current,\n              city,\n              country,\n              continent,\n              "imageUrl": mainImage.asset->.url,\n              "imageAlt": mainImage.alt\n              },\n  "total": count(*[_type == \'store\'\n             && defined(slug.current)\n             && (\n              (!defined($country)) || count($country) == 0 || country in $country\n             )\n             &&(\n              (!defined($continent)) || count($continent) == 0 || continent in $continent\n             )\n             ])\n}': ALL_STORES_QUERYResult;
    '*[_type == \'store\'\n&& slug.current == $slug][0]{\n              name,\n              "slug": slug.current,\n              address1,\n              address2,\n              city,\n              zip,\n              state,\n              country,\n              lat,\n              long,\n              "imageUrl": mainImage.asset->.url,\n              "imageAlt": mainImage.alt\n}': STORE_QUERYResult;
    '*[_type == \'author\'\n && defined(slug.current)]{\n  name,\n  "slug": slug.current,\n  "imageUrl": mainImage.asset->.url,\n  "imageAlt": mainImage.alt\n }': ALL_AUTHORS_QUERYResult;
    '{\n  "author": *[_type == \'author\'\n              && slug.current == $slug][0]{\n              name,\n              "slug": slug.current,\n              body,\n              socialLink,\n              "imageUrl": mainImage.asset->.url,\n              "imageAlt": mainImage.alt\n             },\n  "blogs": *[_type == \'blog\'\n            && author->slug.current == $slug]{\n              name,\n              "slug": slug.current,\n              publishedAt,\n              "imageUrl": mainImage.asset->.url,\n              "imageAlt": mainImage.alt,\n              "category": category->.name,\n              "author": author->.name,\n            }\n}': AUTHOR_QUERYResult;
    '*[\n  _type == \'product\'\n  && defined(slug.current)\n  && (\n    (!defined($search))\n    || name match ($search + "*")\n    || variants[].color->name match ($search + "*")\n    || variants[].size->name match ($search + "*")\n  )\n]{\n  name,\n  "slug": slug.current,\n  "category": category->name,\n  basePrice,\n  "imageUrl": mainImages[0].asset->url,\n  "imageAlt": mainImages[0].alt\n}': SEARCH_PRODUCTS_QUERYResult;
    '*[\n  _type == \'blog\'\n  && defined(slug.current)\n  && (\n    (!defined($search))\n    || name match ($search + "*")\n    || category->name match ($search + "*")\n    || author->name match ($search + "*")\n  )\n]{\n  name,\n  "slug": slug.current,\n  publishedAt,\n  "imageUrl": mainImage.asset->.url,\n  "imageAlt": mainImage.alt,\n  "category": category->.name,\n  "author": author->.name,\n}': SEARCH_BLOGS_QUERYResult;
  }
}
