import type { Metadata } from 'next';
import './globals.css';
import { caveat, nunito, playfair } from '@/lib/fonts';
import { SanityLive } from '@/sanity/lib/live';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: {
    template: '%s | Haru Clothing',
    default: 'Haru Clothing',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-sans', geist.variable)}>
      <body
        className={`${nunito.variable} ${playfair.variable} ${caveat.variable} antialiased`}
      >
        <ClerkProvider>
          {children}
          <SanityLive />
        </ClerkProvider>

        <Toaster richColors closeButton position="bottom-center" />
      </body>
    </html>
  );
}
