import type { Metadata } from 'next';
import './globals.css';
import { caveat, nunito, playfair } from '@/lib/fonts';
import { SanityLive } from '@/sanity/lib/live';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: {
    template: '%s | Haru Clothing',
    default: 'Haru Clothing',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${playfair.variable} ${caveat.variable} antialiased`}
      >
        <ClerkProvider>
          {children}
          <SanityLive />
        </ClerkProvider>
      </body>
    </html>
  );
}
